# -*- coding: utf-8 -*-
"""Módulos personalizados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WJD9h8oCA-Y204JqWWYeH477W81DD_Zd

# Módulos personalizados
"""

import utilitarios as ut

ut.soma(1, 2, 3)

ut.mult(3, 2, 2)

ut.isPalindromo('abc')

ut.isPalindromo('abccba')

t = 'abccba'

t[::-1]

t1 = 'abc'
t1[::-1]

ut.divisao(10,2)